# Generated by Django 2.1.7 on 2019-04-18 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='articles',
            new_name='Article',
        ),
    ]
